### ISSUE TITLE
[Question] Is there a way to reset each lamp after a set time to low light (aka night light)?

### ISSUE THREAD

**Issue by typxyr** [pblesi/touch_light#1]
I'm not a much of coder. I just search the internet until I find answers and patch things together. I have no idea how this would work or be implemented.

**Comment by pblesi** [comment]
The envelopes determine what brightness the light will be after the specified number of clock cycles have passed: https://github.com/pblesi/touch_light/blob/master/src/touch_light.ino#L62-L69

If you modify the second number in each array you can control how quickly the light will dim and go out in order to meet your needs.
