### ISSUE TITLE
Particle Build is not recognizing "#include "wifi_creds.h""

### ISSUE THREAD

**Issue by JoeDACode** [pblesi/touch_light#2]
The Particle Builder is not recognizing #include "wifi_creds.h" and giving me 

lamps.cpp:13:24: wifi_creds.h: No such file or directory

I have no clue what to do about this issue.

**Comment by pblesi** [comment]
Hi @JoeDACode,

It sounds like Particle Builder does not know where to find the file `wifi_creds.h`. I am not familiar with Particle Builder. Is this the particle command line tool? If so, I am able to get this to work by storing the `wifi_creds.h` file in the same directory as my touch_light.ino file (in the `src` directory). I would suggest trying to store `wifi_creds.h` in the same directory as `lamps.cpp` 

If you are not using this file to set wifi credentials on your touch light (because you previously set them when setting up your photon, then you can delete this line (`#include "wifi_creds.h"`) as it is only used for setting wifi creds explicitly through code.

I hope this helps!
